"""empty message

Revision ID: 089ab6cecaa3
Revises: e4b6df0e4d2e
Create Date: 2025-11-22 20:29:09.093750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '089ab6cecaa3'
down_revision = 'e4b6df0e4d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_license', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('doctor_experience', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('doctor_bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('doctor_profilepic', sa.String(length=255), nullable=True))
        batch_op.alter_column('doctor_phone',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['doctor_license'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('patient_bio')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('doctor_phone',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('doctor_profilepic')
        batch_op.drop_column('doctor_bio')
        batch_op.drop_column('doctor_experience')
        batch_op.drop_column('doctor_license')

    # ### end Alembic commands ###
