"""empty message

Revision ID: 10477ecfc3ba
Revises: bd9e5fb953de
Create Date: 2025-12-03 12:38:47.014147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10477ecfc3ba'
down_revision = 'bd9e5fb953de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cun_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pay_method', sa.Enum('cash', 'transfer'), nullable=True))
        batch_op.create_unique_constraint(None, ['pay_ref'])
        batch_op.create_foreign_key(None, 'consultaion', ['cun_id'], ['cun_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pay_method')
        batch_op.drop_column('cun_id')

    # ### end Alembic commands ###
