"""initial schema

Revision ID: 40d0a47c3074
Revises: 
Create Date: 2026-05-31 16:33:47.145415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d0a47c3074'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(length=100), nullable=True),
    sa.Column('admin_password', sa.String(length=200), nullable=True),
    sa.Column('admin_logindate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('patient_fname', sa.String(length=100), nullable=False),
    sa.Column('patient_lname', sa.String(length=100), nullable=False),
    sa.Column('patient_email', sa.String(length=150), nullable=False),
    sa.Column('patient_password', sa.String(length=255), nullable=False),
    sa.Column('patient_address', sa.String(length=255), nullable=True),
    sa.Column('phone_num', sa.String(length=255), nullable=True),
    sa.Column('patient_bio', sa.Text(), nullable=True),
    sa.Column('patient_profilepic', sa.String(length=255), nullable=True),
    sa.Column('patient_dob', sa.Date(), nullable=True),
    sa.Column('patient_regdate', sa.DateTime(), nullable=True),
    sa.Column('patient_gender', sa.Enum('male', 'female', name='patient_gender_enum'), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('patient_email'),
    sa.UniqueConstraint('phone_num')
    )
    op.create_table('specialty',
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('specialty_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('specialty_id')
    )
    op.create_table('doctor',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('doctor_fname', sa.String(length=100), nullable=False),
    sa.Column('doctor_lname', sa.String(length=100), nullable=False),
    sa.Column('doctor_email', sa.String(length=150), nullable=False),
    sa.Column('doctor_phone', sa.String(length=50), nullable=False),
    sa.Column('doctor_license', sa.String(length=100), nullable=False),
    sa.Column('doctor_experience', sa.Integer(), nullable=False),
    sa.Column('doctor_bio', sa.Text(), nullable=True),
    sa.Column('doctor_profilepic', sa.String(length=255), nullable=True),
    sa.Column('doctor_password', sa.String(length=255), nullable=False),
    sa.Column('doctor_address', sa.String(length=255), nullable=True),
    sa.Column('doctor_gender', sa.Enum('male', 'female', name='doctor_gender_enum'), nullable=True),
    sa.Column('doctor_status', sa.Enum('active', 'inactive', name='doctor_status_enum'), nullable=True),
    sa.Column('doctor_regdate', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialty.specialty_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('doctor_email'),
    sa.UniqueConstraint('doctor_license'),
    sa.UniqueConstraint('doctor_phone')
    )
    op.create_table('appointment',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_note', sa.String(length=255), nullable=True),
    sa.Column('doctor_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'cancelled', 'completed', name='appointment_status_enum'), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_table('doctor_schedule',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('monday', sa.Boolean(), nullable=True),
    sa.Column('tuesday', sa.Boolean(), nullable=True),
    sa.Column('wednesday', sa.Boolean(), nullable=True),
    sa.Column('thursday', sa.Boolean(), nullable=True),
    sa.Column('friday', sa.Boolean(), nullable=True),
    sa.Column('saturday', sa.Boolean(), nullable=True),
    sa.Column('sunday', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration', sa.Integer(), nullable=True),
    sa.Column('max_appointments_per_slot', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id'),
    sa.UniqueConstraint('doctor_id')
    )
    op.create_table('consultaion',
    sa.Column('cun_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('diagnose', sa.Text(), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('tests', sa.Text(), nullable=True),
    sa.Column('amt', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['appointment.app_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cun_id')
    )
    op.create_table('payment',
    sa.Column('pay_id', sa.Integer(), nullable=False),
    sa.Column('pay_amt', sa.Float(), nullable=True),
    sa.Column('pay_patientid', sa.Integer(), nullable=False),
    sa.Column('cun_id', sa.Integer(), nullable=True),
    sa.Column('pay_ref', sa.String(length=100), nullable=True),
    sa.Column('pay_method', sa.Enum('cash', 'transfer', name='payment_method_enum'), nullable=True),
    sa.Column('pay_status', sa.Enum('pending', 'failed', 'paid', name='payment_status_enum'), nullable=True),
    sa.Column('pay_data', sa.JSON(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cun_id'], ['consultaion.cun_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_patientid'], ['patient.patient_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pay_id'),
    sa.UniqueConstraint('pay_ref')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('consultaion')
    op.drop_table('doctor_schedule')
    op.drop_table('appointment')
    op.drop_table('doctor')
    op.drop_table('specialty')
    op.drop_table('patient')
    op.drop_table('department')
    op.drop_table('admin')
    # ### end Alembic commands ###
