"""empty message

Revision ID: 41209e4120ab
Revises: 953db62511b8
Create Date: 2025-11-27 23:39:05.048881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41209e4120ab'
down_revision = '953db62511b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_profilepic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('patient_profilepic')

    # ### end Alembic commands ###
