"""Initial migration

Revision ID: 69ecdb128ace
Revises: 
Create Date: 2025-11-06 02:38:32.285715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ecdb128ace'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(length=100), nullable=True),
    sa.Column('admin_password', sa.String(length=200), nullable=True),
    sa.Column('admin_email', sa.String(length=150), nullable=False),
    sa.Column('admin_logindate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email')
    )
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('doctor',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('doctor_fname', sa.String(length=100), nullable=False),
    sa.Column('doctor_lname', sa.String(length=100), nullable=False),
    sa.Column('doctor_password', sa.String(length=255), nullable=False),
    sa.Column('doctor_status', sa.Enum('active', 'inactive'), nullable=True),
    sa.Column('doctor_regdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('patient_fname', sa.String(length=100), nullable=False),
    sa.Column('patient_lname', sa.String(length=100), nullable=False),
    sa.Column('patient_email', sa.String(length=150), nullable=False),
    sa.Column('patient_password', sa.String(length=255), nullable=False),
    sa.Column('patient_address', sa.String(length=255), nullable=False),
    sa.Column('phone_num', sa.String(length=255), nullable=False),
    sa.Column('patient_dob', sa.DateTime(), nullable=True),
    sa.Column('patient_regdate', sa.DateTime(), nullable=True),
    sa.Column('patient_gender', sa.Enum('male', 'female'), nullable=True),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('patient_email'),
    sa.UniqueConstraint('phone_num')
    )
    op.create_table('specialty',
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('specialty_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('specialty_id')
    )
    op.create_table('appointment',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_note', sa.String(length=255), nullable=False),
    sa.Column('doctor_note', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_table('consultaion',
    sa.Column('cun_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('amt', sa.Float(), nullable=True),
    sa.Column('diagnose', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['appointment.app_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cun_id')
    )
    op.create_table('payments',
    sa.Column('pay_id', sa.Integer(), nullable=False),
    sa.Column('pay_amt', sa.Float(), nullable=True),
    sa.Column('pay_patientid', sa.Integer(), nullable=False),
    sa.Column('pay_ref', sa.String(length=100), nullable=True),
    sa.Column('pay_status', sa.Enum('pending', 'failed', 'paid'), nullable=True),
    sa.Column('pay_data', sa.JSON(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pay_patientid'], ['appointment.app_id'], ),
    sa.PrimaryKeyConstraint('pay_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('consultaion')
    op.drop_table('appointment')
    op.drop_table('specialty')
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('department')
    op.drop_table('admin')
    # ### end Alembic commands ###
