"""Initial migration

Revision ID: 8034f34555b4
Revises: 69ecdb128ace
Create Date: 2025-11-06 02:48:13.317314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8034f34555b4'
down_revision = '69ecdb128ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('pay_id', sa.Integer(), nullable=False),
    sa.Column('pay_amt', sa.Float(), nullable=True),
    sa.Column('pay_patientid', sa.Integer(), nullable=False),
    sa.Column('pay_ref', sa.String(length=100), nullable=True),
    sa.Column('pay_status', sa.Enum('pending', 'failed', 'paid'), nullable=True),
    sa.Column('pay_data', sa.JSON(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pay_patientid'], ['appointment.app_id'], ),
    sa.PrimaryKeyConstraint('pay_id')
    )
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('pay_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pay_amt', mysql.FLOAT(), nullable=True),
    sa.Column('pay_patientid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pay_ref', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pay_status', mysql.ENUM('pending', 'failed', 'paid'), nullable=True),
    sa.Column('pay_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('pay_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['pay_patientid'], ['appointment.app_id'], name=op.f('payments_ibfk_1')),
    sa.PrimaryKeyConstraint('pay_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('payment')
    # ### end Alembic commands ###
