"""empty message

Revision ID: 953db62511b8
Revises: 999ac0336154
Create Date: 2025-11-27 10:50:42.780089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953db62511b8'
down_revision = '999ac0336154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_gender', sa.Enum('male', 'female'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('doctor_gender')

    # ### end Alembic commands ###
