"""empty message

Revision ID: a3f01af3339d
Revises: 8034f34555b4
Create Date: 2025-11-06 03:16:12.062772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3f01af3339d'
down_revision = '8034f34555b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('doctor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('appointment_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('appointment_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'doctor', ['doctor_id'], ['doctor_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['patient_id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['department_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'specialty', ['specialty_id'], ['specialty_id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'appointment', ['pay_patientid'], ['app_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payment_ibfk_1'), 'appointment', ['pay_patientid'], ['app_id'])

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')
        batch_op.drop_column('specialty_id')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appointment_ibfk_2'), 'patient', ['patient_id'], ['patient_id'])
        batch_op.create_foreign_key(batch_op.f('appointment_ibfk_1'), 'doctor', ['doctor_id'], ['doctor_id'])
        batch_op.alter_column('doctor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
