"""empty message

Revision ID: b890cf37debd
Revises: 10477ecfc3ba
Create Date: 2025-12-03 19:37:49.924879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b890cf37debd'
down_revision = '10477ecfc3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('admin_email'))
        batch_op.drop_column('admin_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_email', mysql.VARCHAR(length=150), nullable=False))
        batch_op.create_index(batch_op.f('admin_email'), ['admin_email'], unique=True)

    # ### end Alembic commands ###
