"""empty message

Revision ID: bd9e5fb953de
Revises: df49d9cb6a6f
Create Date: 2025-12-02 16:33:07.252792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd9e5fb953de'
down_revision = 'df49d9cb6a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_schedule', schema=None) as batch_op:
        batch_op.drop_column('break_end')
        batch_op.drop_column('break_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('break_start', mysql.TIME(), nullable=True))
        batch_op.add_column(sa.Column('break_end', mysql.TIME(), nullable=True))

    # ### end Alembic commands ###
