"""empty message

Revision ID: d213943225c7
Revises: 31c00dea4736
Create Date: 2025-12-02 04:09:41.383790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd213943225c7'
down_revision = '31c00dea4736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultaion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tests', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultaion', schema=None) as batch_op:
        batch_op.drop_column('tests')
        batch_op.drop_column('medications')
        batch_op.drop_column('treatment')

    # ### end Alembic commands ###
