"""empty message

Revision ID: daa6b549a51f
Revises: e0c276e120ad
Create Date: 2025-11-30 18:24:44.313675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'daa6b549a51f'
down_revision = 'e0c276e120ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('active', 'inactive'), nullable=True))

    # ### end Alembic commands ###
