"""empty message

Revision ID: e0c276e120ad
Revises: e7e8d49f3ad7
Create Date: 2025-11-30 15:13:51.085082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0c276e120ad'
down_revision = 'e7e8d49f3ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('appointment_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('patient_note',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('doctor_note',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('doctor_note',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('patient_note',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('appointment_time')
        batch_op.drop_column('appointment_date')

    # ### end Alembic commands ###
