"""Added new column

Revision ID: e4b6df0e4d2e
Revises: f6960e00595e
Create Date: 2025-11-22 19:55:35.214942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b6df0e4d2e'
down_revision = 'f6960e00595e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('doctor_phone', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['doctor_phone'])
        batch_op.create_unique_constraint(None, ['doctor_email'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'patient', ['pay_patientid'], ['patient_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payment_ibfk_1'), 'appointment', ['pay_patientid'], ['app_id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('doctor_phone')
        batch_op.drop_column('doctor_email')

    # ### end Alembic commands ###
