"""empty message

Revision ID: e7e8d49f3ad7
Revises: 41209e4120ab
Create Date: 2025-11-29 01:37:48.656498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7e8d49f3ad7'
down_revision = '41209e4120ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_address', sa.String(length=255), nullable=True))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('patient_dob',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('patient_dob',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('doctor_address')

    # ### end Alembic commands ###
