"""empty message

Revision ID: f6960e00595e
Revises: a3f01af3339d
Create Date: 2025-11-10 09:09:50.355678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6960e00595e'
down_revision = 'a3f01af3339d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('patient_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('phone_num',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('phone_num',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('patient_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
