"""Add patient email verification fields

Revision ID: fef2a3cc18a8
Revises: 342aacc74311
Create Date: 2026-02-12 13:24:41.721589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef2a3cc18a8'
down_revision = '342aacc74311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('email_verification_expires_at')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
